version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_FASTAPI_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
    volumes:
      - ./backend:/app
      - ./yolo-models:/app/yolo-models

volumes:
  frontend:
  backend:
